import "./styles/global.css";
import {
  Button,
  createTheme,
  Paper,
  Typography
} from "@mui/material";
import ThemeRegistry from "@/theme/ThemeRegistry";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>{children}</body>
      </ThemeRegistry>
    </html>
  );
}
